import type { Entity } from "./ingredient.ts";

/**
 * Produces a STARTER `RecipeScript`-shaped object, not a valid one —
 * `RecipeScriptSchema` requires `sequence.min(1)`, so a scaffold with an
 * empty `sequence` is intentionally schema-invalid the moment it's
 * written; this module never calls `RecipeScriptSchema.parse` on its own
 * output. `initialInventory` entity ids ARE checked against the real
 * entity catalog (throws on an unknown one). See
 * `reference/recipe-scaffold.md` for design rationale.
 */

export interface RecipeScaffoldInput {
  /** Recipe id AND the basis for `names.en` — pass a filename stem (e.g.
   *  "quick-fried-potatoes"), not a pre-built id. */
  slug: string;
  /** Real entity ids for `initialInventory` — validated against the
   *  loaded entity catalog. */
  entityIds: string[];
}

/** A plain object matching `RecipeScriptSchema`'s SHAPE, not
 *  `RecipeScript` — an empty `sequence` makes it schema-invalid by
 *  construction. */
export interface RecipeScaffold {
  id: string;
  names: { en: string };
  initialInventory: { id: string; entityId: string; state: string; tags: string[] }[];
  availableTools: string[];
  sequence: never[];
  metadata: { notes: string };
}

function slugToId(slug: string): string {
  return slug.replace(/[-\s]+/g, "_").toLowerCase();
}

function slugToDisplayName(slug: string): string {
  return slug
    .replace(/[-_]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(" ");
}

export function buildRecipeScaffold(
  input: RecipeScaffoldInput,
  entities: Map<string, Entity>
): RecipeScaffold {
  if (input.entityIds.length === 0) {
    throw new Error(
      "buildRecipeScaffold: at least one entity id is required for initialInventory (RecipeScriptSchema requires min(1))."
    );
  }

  // Instance ids are numbered PER ENTITY TYPE, independently starting at
  // 1 (egg-1, oil-1, salt-1 all coexist) — not one shared counter. See
  // reference/recipe-scaffold.md.
  const countPerEntity = new Map<string, number>();
  const initialInventory = input.entityIds.map((entityId) => {
    const entity = entities.get(entityId);
    if (!entity) {
      throw new Error(
        `buildRecipeScaffold: unknown entity id "${entityId}" — check data/entities/*.json for the real id.`
      );
    }
    if (entity.possibleStates.length === 0) {
      throw new Error(
        `buildRecipeScaffold: entity "${entityId}" has no possibleStates — cannot pick a starting state for it.`
      );
    }
    const n = (countPerEntity.get(entityId) ?? 0) + 1;
    countPerEntity.set(entityId, n);
    return {
      id: `${entityId}-${n}`,
      entityId,
      // possibleStates[0] is a documented DEFAULT, not a claim it's
      // always the right starting state. See reference/recipe-scaffold.md.
      state: entity.possibleStates[0],
      tags: [],
    };
  });

  return {
    id: slugToId(input.slug),
    names: { en: slugToDisplayName(input.slug) },
    initialInventory,
    availableTools: [],
    sequence: [],
    metadata: {
      notes:
        "Scaffold generated by `npm run new-recipe` (src/recipe-scaffold.ts) — NOT yet a valid recipe. " +
        "`sequence` is intentionally empty (RecipeScriptSchema requires at least one step) and `availableTools` " +
        "is empty too. Add steps referencing data/actions/*.json (check each action's requiredTools/" +
        "requiredToolCapabilities/requiredIngredientCapabilities/parameters), then run " +
        "`npm run validate-recipe -- <this file>` and follow AUTHORING.md's loop until it passes cleanly.",
    },
  };
}
